# ─── General ─────────────────────────────────────────────
term xterm-256color
allow_remote_control yes
listen_on unix:/tmp/kitty.sock

# ─── Ventana ─────────────────────────────────────────────
initial_window_width 80c
initial_window_height 19c
window_border_width 0
background_opacity 0.95
window_padding_width 6

# ─── Fuente ──────────────────────────────────────────────
font_family FiraCode Nerd Font
bold_font FiraCode Nerd Font Bold
italic_font FiraCode Nerd Font Italic
font_size 9.0

# ─── Colores ─────────────────────────────────────────────
include ~/.local/state/theme/kitty.conf

# ─── Copiar y pegar ─────────────────────────────────────
map ctrl+alt+c copy_to_clipboard
map ctrl+alt+v paste_from_clipboard
map shift+page_up scroll_page_up
map shift+page_down scroll_page_down
map shift+home scroll_home
map shift+end scroll_end

# ─── Ratón ───────────────────────────────────────────────
# map mouse button2 press paste_from_selection

# ─── Scroll ──────────────────────────────────────────────
scrollback_lines 10000
scrollback_pager less --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER

# ─── Font Size ───────────────────────────────────────────
map ctrl+0 change_font_size all 0
map ctrl+minus change_font_size all -2.0
map ctrl+equal change_font_size all +2.0
