# Catppuccin Mocha (dark) — override de colores para hyprlock
$base    = rgb(1e1e2e)
$crust   = rgb(11111b)
$text    = rgb(cdd6f4)
$subtext = rgb(a6adc8)
$accent  = rgb(b4befe)
$inner   = rgb(313244)
$red     = rgb(f38ba8)
