# --- Defaults (Mocha) ---
$base    = rgb(1e1e2e)
$crust   = rgb(11111b)
$text    = rgb(cdd6f4)
$subtext = rgb(a6adc8)
$accent  = rgb(b4befe)
$inner   = rgb(313244)
$red     = rgb(f38ba8)

# --- Override based on active theme (dark/light) ---
source = $HOME/.local/state/theme/hyprlock-colors.conf

general {
    hide_cursor = true
    grace = 0
    disable_loading_bar = true
    ignore_empty_input = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 2
    blur_size = 6
    noise = 0.0117
    contrast = 1.0
    brightness = 0.85
    vibrancy = 0.15
}

# Clock
label {
    monitor =
    text = cmd[update:1000] echo "$(date '+%H:%M')"
    color = $text
    font_size = 68
    font_family = FiraCode Nerd Font
    position = 72, 232
    halign = left
    valign = bottom
}

# Date
label {
    monitor =
    text = cmd[update:60000] echo "$(date '+%A, %d %B')"
    color = $subtext
    font_size = 15
    font_family = FiraCode Nerd Font
    position = 76, 208
    halign = left
    valign = bottom
}

# Username
label {
    monitor =
    text = 󰀄  $USER
    color = $accent
    font_size = 13
    font_family = FiraCode Nerd Font
    position = 76, 150
    halign = left
    valign = bottom
}

# Input
input-field {
    monitor =
    size = 280, 46
    outline_thickness = 1
    dots_size = 0.25
    dots_spacing = 0.3
    dots_center = true
    rounding = 10
    outer_color = $inner
    inner_color = $inner
    font_color = $text
    fail_color = $red
    check_color = $accent
    fade_on_empty = false
    placeholder_text = <span foreground="##a6adc8">Contraseña</span>
    hide_input = false
    position = 76, 84
    halign = left
    valign = bottom
}
