# Catppuccin Latte (light) — override de colores para hyprlock
$base    = rgb(eff1f5)
$crust   = rgb(dce0e8)
$text    = rgb(4c4f69)
$subtext = rgb(6c6f85)
$accent  = rgb(7287fd)
$inner   = rgb(ccd0da)
$red     = rgb(d20f39)
